// ESLint flat config. Replaces .eslintrc.json (eslintrc format, removed).
//
// Named .mjs deliberately: package.json has no "type": "module", so a .js file
// here would be parsed as CommonJS and the import below would throw at load.
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

// ---------------------------------------------------------------------------
// P0.2 / P6.1 / P10.6 — the custom rule the enforcement table (P19) has always
// owed and that has never existed. Every displayed value resolves from a token,
// from the database, or from lib/format.ts. None of them is typed into a file.
//
// It walks string Literals and TemplateElements only, so prose in comments —
// the em dashes all over this codebase — is invisible to it by construction.
// ---------------------------------------------------------------------------
const BANNED = [
  {
    id: "hex",
    // P6.1's own regex, verbatim.
    test: /#[0-9a-fA-F]{3,8}\b/,
    message:
      "Raw hex colour. Every colour resolves from styles/tokens.css (P6.1). If the token is missing, the architecture doc gains it first (P6.2).",
  },
  {
    id: "naira",
    test: /₦/,
    message:
      "Inline naira symbol. Currency renders only through formatNaira() in lib/format.ts (P10.6).",
  },
  {
    id: "glyph",
    // ▲ ▼ only. The em dash is NOT included: it is load-bearing punctuation all
    // over this codebase (`join(" — ")`, `&mdash;` in the unavailable badge) and no
    // regex separates "no-change glyph" from "prose dash". A check that cries wolf
    // on correct code is a check someone deletes — see check-seed.sh's own header.
    test: /[▲▼]/,
    message:
      "Hardcoded direction glyph. The arrow is part of the formatted change string, not a literal (P6.4, P0.2).",
  },
  {
    id: "comma-numeral",
    test: /\d{1,3}(?:,\d{3})+/,
    message:
      "Comma-formatted numeral. Figures are query results formatted by lib/format.ts, never string literals (P0.2, P10.6).",
  },
];

const protocol = {
  rules: {
    "no-hardcoded-display-values": {
      meta: {
        type: "problem",
        docs: { description: "No typed-in colours, currency, glyphs or figures (P0.2, P6.1, P10.6)." },
        schema: [],
      },
      create(context) {
        const check = (node, text) => {
          if (typeof text !== "string") return;
          for (const rule of BANNED) {
            if (rule.test.test(text)) {
              context.report({ node, message: `${rule.message} [P-lint:${rule.id}]` });
            }
          }
        };
        return {
          Literal: (node) => check(node, typeof node.value === "string" ? node.value : null),
          TemplateElement: (node) => check(node, node.value.cooked),
          JSXText: (node) => check(node, node.value),
        };
      },
    },
  },
};

const config = [
  // 1:1 with the .eslintrc.json this file replaces.
  ...compat.extends("next/core-web-vitals", "next/typescript"),

  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "playwright-report/**",
      "types/database.ts",
      // Generated by Next, gitignored, and stamped "should not be edited". Its
      // triple-slash references are Next's, not ours. `next lint` skips it
      // automatically; that masking disappears with Next 16, so the exclusion
      // is written down here rather than inherited.
      "next-env.d.ts",
    ],
  },

  {
    files: ["app/**/*.{ts,tsx}", "components/**/*.{ts,tsx}", "lib/**/*.{ts,tsx}"],
    plugins: { protocol },
    rules: { "protocol/no-hardcoded-display-values": "error" },
  },

  // lib/format.ts IS the currency/week boundary — it is the one file that must
  // hold ₦ and grouping separators. Everything else routes through it.
  {
    files: ["lib/format.ts"],
    rules: { "protocol/no-hardcoded-display-values": "off" },
  },

  // Tests assert on formatted OUTPUT: "₦95,000", "▲ 2.4%", "#8A9AB6" are the
  // expected values, so banning them here would ban testing the formatter.
  {
    files: ["**/*.test.{ts,tsx}", "**/*.spec.{ts,tsx}", "e2e/**"],
    rules: { "protocol/no-hardcoded-display-values": "off" },
  },
];

export default config;
